# generated by mkexr.rb

EXERB  = exerb
OUTPUT = cal.exe
INPUT  = cal.exr
FILES  = cal.rb calendar.rb D:/ruby/ruby/lib/ruby/1.8/date.rb D:/ruby/ruby/lib/ruby/1.8/date/format.rb default_holidays.rb D:/ruby/ruby/lib/ruby/1.8/optparse.rb D:/ruby/ruby/lib/ruby/1.8/rational.rb

all: $(OUTPUT)

$(OUTPUT): $(INPUT) $(FILES)
	$(EXERB) $(INPUT)
	chmod +x $(OUTPUT)

go: all
	$(OUTPUT)

clean:
	rm $(OUTPUT)
